### ISSUE TITLE
Missing example when using contextType in class component?

### ISSUE THREAD

**Issue by binoy14** [piotrwitek/react-redux-typescript-guide#140]
Looks like the Context section is missing an example when using in a class using `contextType`. I am happy to make a PR, if thats the case.

I believe it would look something like this. Please provide me feedback if that is incorrect, I found it in the [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L370)

**Theme Context**

```tsx
import * as React from 'react';

export type Theme = React.CSSProperties;

type Themes = {
  dark: Theme;
  light: Theme;
};

export const themes: Themes = {
  dark: {
    color: 'black',
    backgroundColor: 'white',
  },
  light: {
    color: 'white',
    backgroundColor: 'black',
  },
};

export type ThemeContextProps = { theme: Theme; toggleTheme?: () => void };
const ThemeContext = React.createContext<ThemeContextProps>({ theme: themes.light });

export default ThemeContext;
```

**Using contextType in class based component**
```tsx
import * as React from "react";
import ThemeContext from "./ThemeContext";

export class MyComponent extends React.Component {

  static contextType: ThemeContext;
  context!: React.ContextType<typeof ThemeContext>;
  
  render() {
    return (
      <div>Theme is {this.context.theme}</div>
    );
  }
}
```

**Comment by piotrwitek** [comment]
Hey @binoy14, thanks for your suggestion!

Yes please go for it! 👍 

After this section: https://github.com/piotrwitek/react-redux-typescript-guide#themeconsumer

Please add a heading: ThemeConsumer in class component

I would not introduce a new example but rather adapted existing `ToggleThemeButton `, primarly because it's easier for people that are learning to clearly see the differences, second `ToggleThemeButton` is better because include not only value but also handler example which is more complete.

Something like this:
```tsx
import * as React from 'react';
import ThemeContext from './theme-context';

type Props = {};

export class ToggleThemeButton extends React.Component<Props> {
	static contextType: ThemeContext;
	context!: React.ContextType<typeof ThemeContext>;

	render() {
		const { theme, toggleTheme } = this.context;
		return (
		    <button style={theme} onClick={toggleTheme}>
		        Toggle Theme
            </button>
		);
	}
}
```

**Comment by binoy14** [comment]
@piotrwitek Thanks for the feedback, I will make a PR soon
