### ISSUE TITLE
Typescript-fsa

### ISSUE THREAD

**Issue by rclmenezes** [piotrwitek/react-redux-typescript-guide#27]
I'm curious about your opinion on using `typescript-fsa` for actions/reducers:

https://github.com/aikoven/typescript-fsa

**Comment by piotrwitek** [comment]
Hello @rclmenezes, 
You can check this section as I think some of the points will also apply to `typescript-fsa`.
Moreover `typescript-fsa` is using `type` property which is not good design decision. I was using it as well long ago and it was OK, but the situation changed with newest typings and improved TypeScript type inference, that's why I dropped it's use and adapted new solutions.
For instance:
- you can make mistake and pass action creator as action, because it have `type` prop and compiler will not see the error
- second because of the `type` prop on action creator you will have issues with `connect` when passing action creators as props to you handlers in components, because you declare it like this: `() => void` compiler will yell at you about the excess `type` prop in action creator

So if you really want to retain complete type soundness across your application while leveraging type inference as much as possible I recommend you to check a new generation lib [`typesafe-actions`](https://github.com/piotrwitek/typesafe-actions#motivation) which I made specifically for that purpose. It's also simple and functional, please check the newest [Tutorial section](https://github.com/piotrwitek/typesafe-actions#tutorial).

When I have time I'll make a separate comparison of `typescript-fsa` with `typesafe-actions`.

**Comment by rclmenezes** [comment]
Thanks for the explanation!

**Comment by QuantumInformation** [comment]
I wouldn't use typescript-fsa either, I'm stripping it out of a project I inherited.
