### ISSUE TITLE
Interface better than type alias.

### ISSUE THREAD

**Issue by mrdulin** [piotrwitek/react-redux-typescript-guide#3]
original:

```ts
type Props = {
  className?: string,
  style?: React.CSSProperties,
};
```

better:
```ts
interface Props = {
  className?: string,
  style?: React.CSSProperties,
}
```

what do you say?

**Comment by piotrwitek** [comment]
@mrdulin hello :)
I written some relevant points here: https://github.com/piotrwitek/react-redux-typescript-guide#--differences-between-interface-declarations-and-type-aliases

I haven't noticed a significant difference or limitations in both approaches during my project experience, but now I would prefer to use interface, with tslint [interface-name](https://palantir.github.io/tslint/rules/interface-name/) rule enabled, because this make my imports from **big modules** easier, because of clear distinction between classes, const's and interfaces.

But in case of **one class modules** like React components, there is really no difference to me only the consistency with rest of the codebase is important.

**Comment by piotrwitek** [comment]
closing, nothing more to add here
