### ISSUE TITLE
example of state merging in reducer not compliant with TS v2.4

### ISSUE THREAD

**Issue by khell** [piotrwitek/react-redux-typescript-guide#4]
Hi,

Thank you for the guide.

How would you recommend the example on "Spread operation with Exact Types check to guard against excess or mismatched props" be used with strictNullChecks? As a `Partial` makes all properties nullable, it is required to define all State in this form:

```javascript
export type State = {
  readonly counter: number | undefined,
  readonly baseCurrency: string | undefined,
};
```

This is the same as effectively switching strictNullChecks off. Is there any other way?

Cheers.

**Comment by piotrwitek** [comment]
Hi @khell,
I'm curious why you think that it is required to define all State props in nullable form?
Is it something in the guide misleading you?

Have you checked the playground link to play with it yourself (the goodReducer example)?
The solution works with TS 2.3 and you can guard against mismatched props.

It will probably break in next release v2.4 because they changed how spread is typed, but I'm working on that and will update the guide accordingly.

**Comment by khell** [comment]
Ah, I was using Typescript 2.4 somehow and ran into https://github.com/Microsoft/TypeScript/issues/16509. Thanks for the assistance.

**Comment by piotrwitek** [comment]
@khell no problem, it's good that you have pointed out an issue as this is something that need to be revised and handled for v2.4
I'll keep it open for tracking

**Comment by piotrwitek** [comment]
the related issue is fixed https://github.com/Microsoft/TypeScript/issues/16509

**Comment by piotrwitek** [comment]
also guide was updated to reflect changes and the problem does not exist anymore :)
please check: https://github.com/piotrwitek/react-redux-typescript-guide/blob/8ccf66955d42d03151cc1e53b58af5eff2b0a237/README.md#reducer-with-classic-const-types
