### ISSUE TITLE
Component unrelated to interface in spread attributes example

### ISSUE THREAD

**Issue by cstafie** [piotrwitek/react-redux-typescript-guide#98]
![screen shot 2018-09-20 at 12 02 14 pm](https://user-images.githubusercontent.com/26175864/45831382-31864200-bccd-11e8-9d6e-855a843492a3.png)

**Comment by cstafie** [comment]
Maybe I just don't understand the example, but shouldn't the interface be specifying types for children and restProps instead of className and style?

**Comment by piotrwitek** [comment]
I understand that not every one knows that, so in a nutshell:
- generic children is automatically included in React.SFC type and in this case it's a generic children
- className and style is just what we need for this component
- restProps is a spread, which is helpful to more concisely pass the props to a wrapper div instead of doing it one by one
